 # Introducción a NumPy



 NumPy es una biblioteca esencial para la computación científica en Python. Proporciona estructuras de datos y funciones para manejar arrays multidimensionales de manera eficiente. En esta sección, aprenderemos a crear y manipular arrays usando NumPy, una herramienta indispensable en el análisis de datos, la ciencia de datos y la computación numérica.

 ## Crear Arrays a partir de Listas de Python



 La forma más común de crear un array en NumPy es mediante la conversión de una lista de Python usando la función `np.array()`. Esto es útil cuando queremos aprovechar las capacidades de cálculo y manipulación de arrays de NumPy.

In [1]:
import numpy as np  # Importamos NumPy y usamos el alias común 'np'.


In [2]:
np.array([1, 2, 3, 4, 5])  # Convertimos la lista [1, 2, 3, 4, 5] en un array de NumPy.

array([1, 2, 3, 4, 5])

 El código anterior convierte una lista de Python en un array de NumPy. Esto nos permite acceder a las poderosas funciones y operaciones de NumPy que no están disponibles para listas normales de Python.

 ## Especificar el Tipo de Datos de un Array



 NumPy permite definir explícitamente el tipo de datos del array usando el argumento `dtype`. Esto puede ser importante para el manejo de memoria y precisión en cálculos numéricos, especialmente al trabajar con tipos específicos como `float` o `int`.

In [3]:
np.array([1, 2, 3, 4, 5], dtype='float32')  # Creamos un array de tipo 'float32' a partir de una lista.

array([1., 2., 3., 4., 5.], dtype=float32)

 Aquí hemos convertido la lista `[1, 2, 3, 4, 5]` en un array de números de punto flotante de precisión simple (`float32`). Esto puede ser útil para garantizar la precisión numérica o reducir el uso de memoria.

 ## Crear Arrays Multidimensionales



 Los arrays multidimensionales son útiles para representar matrices y datos tabulares. NumPy facilita la creación de arrays de dimensiones superiores.

In [4]:
np.array([range(i, i + 3) for i in [2, 4, 6]])  # Creamos un array 2D donde cada sublista es una fila.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

 El código anterior genera un array bidimensional (una matriz) con filas `[2, 3, 4]`, `[4, 5, 6]` y `[6, 7, 8]`. Esto se logra utilizando una lista de comprensión.

 ## Creación de Arrays desde Cero



 NumPy ofrece funciones para crear arrays grandes sin necesidad de convertir listas. Esto es útil para la inicialización rápida de matrices.

 ### Crear un Array de Ceros



 `np.zeros` crea un array de un tamaño específico, inicializando todos los valores a `0`.

In [5]:
np.zeros(10, dtype=int)  # Crea un array de 10 elementos, todos inicializados a cero.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 ### Crear un Array de Unos



 `np.ones` crea un array lleno de `1`s con dimensiones especificadas. Esto puede ser útil para cálculos donde necesitamos matrices de referencia.

In [6]:
np.ones((3, 5), dtype=float)  # Crea un array de 3 filas y 5 columnas lleno de unos, con tipo `float`.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

 ### Crear un Array Lleno de un Valor Constante



 `np.full` permite crear un array donde cada elemento tiene un valor específico.

In [7]:
np.full((3, 5), 3.14)  # Crea un array 3x5 con todos los valores igual a `3.14`.

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

 ### Crear un Array Usando `np.arange`



 `np.arange` es similar a `range` en Python, pero devuelve un array en lugar de una lista.

In [8]:
np.arange(0, 20, 2)  # Genera un array con valores del 0 al 18, con un paso de 2.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

 ### Crear un Array de Valores Equidistantes con `np.linspace`



 `np.linspace` genera un número fijo de puntos equidistantes entre un valor inicial y uno final, ambos inclusivos.

In [9]:
np.linspace(0, 1, 5)  # Genera un array con 5 valores equidistantes entre 0 y 1.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 ### Generar Valores Aleatorios con NumPy



 NumPy ofrece una variedad de funciones para generar números aleatorios. Aquí usaremos un generador de números aleatorios para crear arrays.

In [10]:
rng = np.random.default_rng(seed=42)  # Creamos un generador de números aleatorios con una semilla para reproducibilidad.
rng.random((3, 3))  # Genera un array 3x3 de valores aleatorios en el intervalo [0, 1).

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

 ### Generar Valores Aleatorios con Distribución Normal



 `rng.normal` genera valores distribuidos normalmente con una media y desviación estándar especificadas.

In [11]:
rng.normal(0, 1, (3, 3))  # Genera un array 3x3 de valores con distribución normal (media=0, desviación estándar=1).

array([[-0.85304393,  0.87939797,  0.77779194],
       [ 0.0660307 ,  1.12724121,  0.46750934],
       [-0.85929246,  0.36875078, -0.9588826 ]])

 ### Generar Enteros Aleatorios



 `rng.integers` crea un array de enteros aleatorios dentro de un rango específico.

In [12]:
rng.integers(0, 10, (3, 3))  # Genera un array 3x3 de enteros aleatorios entre 0 y 9.

array([[8, 8, 2],
       [6, 1, 7],
       [7, 3, 0]], dtype=int64)

 ### Crear una Matriz Identidad



 Una matriz identidad es una matriz cuadrada con `1`s en la diagonal principal y `0`s en el resto. Se usa comúnmente en operaciones de álgebra lineal.

In [13]:
np.eye(3)  # Crea una matriz identidad de 3x3.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### Crear un Array Vacío



 `np.empty` crea un array no inicializado, lo que significa que sus valores iniciales dependerán del contenido de la memoria en el momento de la creación.

In [14]:
np.empty(3)  # Crea un array de tamaño 3 sin inicializar.

array([1., 1., 1.])