 # Fundamentos de los Arrays de NumPy



 La manipulación de datos en Python se asocia estrechamente con el uso de los arrays de NumPy. Muchas herramientas modernas, como Pandas, se construyen sobre la base de estos arrays, lo que hace fundamental comprender su funcionamiento. En esta sección, exploraremos cómo acceder a los datos y subarrays, así como cómo dividir, reorganizar y combinar arrays. Aunque estas operaciones básicas pueden parecer simples, constituyen los pilares para tareas más avanzadas y sofisticadas. Familiarízate bien con ellas para aprovechar al máximo NumPy.



 A continuación, cubriremos varias categorías de manipulación de arrays:



 - **Atributos de arrays**: Cómo determinar el tamaño, forma, consumo de memoria y tipos de datos de los arrays.

 - **Indexación de arrays**: Cómo obtener y modificar elementos individuales de un array.

 - **Rebanado (slicing) de arrays**: Cómo acceder y modificar subarrays.

 - **Reorganización de arrays**: Cómo cambiar la forma de un array existente.

 - **Unión y división de arrays**: Cómo combinar múltiples arrays en uno o dividir uno en varios.

 ## Atributos de los Arrays en NumPy



 Vamos a empezar definiendo tres arrays aleatorios de una, dos y tres dimensiones, utilizando el generador de números aleatorios de NumPy. Utilizaremos una semilla para garantizar que se generen los mismos números cada vez que ejecutemos el código.

In [1]:
import numpy as np  # Importamos la biblioteca NumPy y la referenciamos con el alias 'np'.

rng = np.random.default_rng(0)  # Creamos un generador de números aleatorios con una semilla fija.
x1 = rng.integers(10, size=6)  # Array unidimensional con 6 elementos aleatorios entre 0 y 9.
x2 = rng.integers(10, size=(3, 4))  # Array bidimensional de tamaño 3x4 con elementos aleatorios.
x3 = rng.integers(10, size=(3, 4, 5))  # Array tridimensional de tamaño 3x4x5 con elementos aleatorios.


 Los arrays de NumPy tienen varios atributos útiles, como `ndim` (número de dimensiones), `shape` (tamaño de cada dimensión) y `size` (número total de elementos).

In [2]:
print(f"""
x3 ndim:  {x3.ndim}  # Muestra el número de dimensiones del array `x3`.
x3 shape: {x3.shape}  # Muestra el tamaño de cada dimensión del array `x3`.
x3 size:  {x3.size}  # Muestra el número total de elementos en el array `x3`.
""")



x3 ndim:  3  # Muestra el número de dimensiones del array `x3`.
x3 shape: (3, 4, 5)  # Muestra el tamaño de cada dimensión del array `x3`.
x3 size:  60  # Muestra el número total de elementos en el array `x3`.



 Otro atributo importante es `dtype`, que muestra el tipo de datos de los elementos en el array.

In [3]:
print("dtype:", x3.dtype)  # Muestra el tipo de datos de los elementos en `x3`.


dtype: int64


 Los atributos `itemsize` y `nbytes` proporcionan información sobre el tamaño en bytes de cada elemento y el tamaño total del array, respectivamente.

In [4]:
print(f"""
itemsize: {x3.itemsize} bytes  # Tamaño en bytes de cada elemento del array `x3`.
nbytes: {x3.nbytes} bytes  # Tamaño total en bytes del array `x3`.
""")



itemsize: 8 bytes  # Tamaño en bytes de cada elemento del array `x3`.
nbytes: 480 bytes  # Tamaño total en bytes del array `x3`.



 En general, `nbytes` es igual a `itemsize` multiplicado por `size`, lo que nos indica el espacio total que ocupa el array en memoria.

 ## Indexación de Arrays: Acceso a Elementos Individuales



 La indexación de elementos en un array de NumPy es similar a la indexación en listas de Python. En un array unidimensional, puedes acceder al elemento en la posición `i` usando corchetes.

In [5]:
print(f"""
Mostramos el array `x1`:
{x1}

Accedemos al primer elemento del array `x1`:
{x1[0]}

Accedemos al quinto elemento del array `x1`:
{x1[4]}
""")



Mostramos el array `x1`:
[8 6 5 2 3 0]

Accedemos al primer elemento del array `x1`:
8

Accedemos al quinto elemento del array `x1`:
3



 También podemos usar índices negativos para acceder a los elementos desde el final del array.

In [6]:
print(f"""
Último elemento del array `x1`:
{x1[-1]}

Penúltimo elemento del array `x1`:
{x1[-2]}
""")



Último elemento del array `x1`:
0

Penúltimo elemento del array `x1`:
3



 En arrays multidimensionales, accedemos a los elementos mediante una tupla de índices separados por comas.

In [7]:
print(f"""
Mostramos el array bidimensional `x2`:
{x2}

Primer elemento de la primera fila del array `x2`:
{x2[0, 0]}

Primer elemento de la tercera fila del array `x2`:
{x2[2, 0]}

Último elemento de la tercera fila del array `x2`:
{x2[2, -1]}
""")



Mostramos el array bidimensional `x2`:
[[0 0 1 8]
 [6 9 5 6]
 [9 7 6 5]]

Primer elemento de la primera fila del array `x2`:
0

Primer elemento de la tercera fila del array `x2`:
9

Último elemento de la tercera fila del array `x2`:
5



 Podemos modificar los valores de los elementos utilizando la misma notación de índice.

In [8]:
x2[0, 0] = 12  # Modificamos el primer elemento de la primera fila de `x2`.
print(f"""
Array `x2` después de modificar el primer elemento de la primera fila:
{x2}
""")



Array `x2` después de modificar el primer elemento de la primera fila:
[[12  0  1  8]
 [ 6  9  5  6]
 [ 9  7  6  5]]



 A diferencia de las listas de Python, los arrays de NumPy tienen un tipo de dato fijo. Esto significa que si intentamos asignar un valor de un tipo diferente, se realizará una conversión automática, posiblemente truncando el valor.

In [9]:
x1[0] = 3.14159  # El valor de punto flotante será truncado al convertirlo a un entero.
print(f"""
Array `x1` después de asignar un valor de punto flotante truncado:
{x1}
""")



Array `x1` después de asignar un valor de punto flotante truncado:
[3 6 5 2 3 0]



 ## Rebanado (Slicing) de Arrays: Acceso a Subarrays



 Podemos acceder a subarrays utilizando la notación de slicing (rebanado) con el carácter `:`. La sintaxis general para un slicing es `x[start:stop:step]`.

In [10]:
x = np.arange(10)  # Creamos un array con valores del 0 al 9.
print(f"""
Primeros cinco elementos:
{x[:5]}

Elementos a partir del índice 5:
{x[5:]}

Subarray del índice 4 al 6:
{x[4:7]}

Elementos con paso de 2:
{x[::2]}

Elementos a partir del índice 1 con paso de 2:
{x[1::2]}
""")



Primeros cinco elementos:
[0 1 2 3 4]

Elementos a partir del índice 5:
[5 6 7 8 9]

Subarray del índice 4 al 6:
[4 5 6]

Elementos con paso de 2:
[0 2 4 6 8]

Elementos a partir del índice 1 con paso de 2:
[1 3 5 7 9]



 El paso negativo nos permite invertir el orden del array.

In [11]:
x = np.arange(10)  # Creamos un array con valores del 0 al 9.
print(f"""
Mostrar el array `x`: {x}
    ---
Mostrar los elementos en orden inverso: {x[::-1]}
Mostrar los elementos en orden inverso desde el índice 5 con paso de 2: {x[5::-2]}
""")



Mostrar el array `x`: [0 1 2 3 4 5 6 7 8 9]
    ---
Mostrar los elementos en orden inverso: [9 8 7 6 5 4 3 2 1 0]
Mostrar los elementos en orden inverso desde el índice 5 con paso de 2: [5 3 1]



 ## Subarrays Multidimensionales



 Los subarrays en arrays multidimensionales funcionan de manera similar, pero podemos aplicar múltiples slicing separados por comas.

In [12]:
print(f"""
Primeras dos filas y primeras tres columnas de `x2`:
{x2[:2, :3]}

Todas las filas, cada dos columnas:
{x2[:, ::2]}
""")


Primeras dos filas y primeras tres columnas de `x2`:
[[12  0  1]
 [ 6  9  5]]

Todas las filas, cada dos columnas:
[[12  1]
 [ 6  5]
 [ 9  6]]



 También podemos invertir dimensiones combinando slicing.

In [13]:
print(f"""
Invierte filas y columnas del array `x2`:
{x2[::-1, ::-1]}
""")



Invierte filas y columnas del array `x2`:
[[ 5  6  7  9]
 [ 6  5  9  6]
 [ 8  1  0 12]]



 ## Acceso a Filas y Columnas en Arrays



 Es común acceder a filas o columnas individuales. Esto se puede lograr combinando la indexación y el slicing.

In [14]:
print(f"""
Primera columna de `x2`:
{x2[:, 0]}

Primera fila de `x2`:
{x2[0, :]}

Equivalente a `x2[0, :]`:
{x2[0]}
""")



Primera columna de `x2`:
[12  6  9]

Primera fila de `x2`:
[12  0  1  8]

Equivalente a `x2[0, :]`:
[12  0  1  8]



 ## Subarrays como Vistas Sin Copias



 Cuando realizamos slicing de un array en NumPy, se crea una vista, no una copia. Esto significa que las modificaciones en el subarray afectan al array original.

In [15]:
x2_sub = x2[:2, :2]  # Extraemos un subarray 2x2.
print(f"""
Subarray extraído (x2_sub):
{x2_sub}
""")
x2_sub[0, 0] = 99  # Modificamos el subarray.
print(f"""
Subarray modificado (x2_sub):
{x2_sub}

Array original modificado (x2):
{x2}
""")



Subarray extraído (x2_sub):
[[12  0]
 [ 6  9]]


Subarray modificado (x2_sub):
[[99  0]
 [ 6  9]]

Array original modificado (x2):
[[99  0  1  8]
 [ 6  9  5  6]
 [ 9  7  6  5]]



 Si necesitamos una copia del subarray para que los cambios no afecten al array original, podemos usar `copy()`.

In [16]:
x2_sub_copy = x2[:2, :2].copy()  # Creamos una copia del subarray.
x2_sub_copy[0, 0] = 42  # Modificamos la copia.

print(f"""
Copia del subarray modificada (x2_sub_copy):
{x2_sub_copy}

Array original (x2) no se ve afectado:
{x2}
""")



Copia del subarray modificada (x2_sub_copy):
[[42  0]
 [ 6  9]]

Array original (x2) no se ve afectado:
[[99  0  1  8]
 [ 6  9  5  6]
 [ 9  7  6  5]]



 ## Reorganización de Arrays



 Podemos cambiar la forma de un array con el método `reshape()`. Por ejemplo, podemos reorganizar números del 1 al 9 en una cuadrícula de 3x3.

In [17]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


 La conversión de arrays unidimensionales a matrices de fila o columna también es común.

In [18]:
x1 = np.array([1, 2, 3])
print(f"""
Convertimos `x1` en un vector fila usando reshape:
{x1.reshape((1, 3))}

Usamos `np.newaxis` para convertirlo en un vector fila:
{x1[np.newaxis, :]}

Convertimos `x1` en un vector columna usando reshape:
{x1.reshape((3, 1))}

Usamos `np.newaxis` para convertirlo en un vector columna:
{x1[:, np.newaxis]}
""")



Convertimos `x1` en un vector fila usando reshape:
[[1 2 3]]

Usamos `np.newaxis` para convertirlo en un vector fila:
[[1 2 3]]

Convertimos `x1` en un vector columna usando reshape:
[[1]
 [2]
 [3]]

Usamos `np.newaxis` para convertirlo en un vector columna:
[[1]
 [2]
 [3]]



 ## Concatenación y División de Arrays



 Podemos combinar múltiples arrays en uno con funciones como `np.concatenate`, `np.vstack` y `np.hstack`, y también dividir un array en varios subarrays.

In [19]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]

print(f"""
Concatenamos `x` e `y`:
{np.concatenate([x, y])}

Concatenamos `x`, `y` y `z`:
{np.concatenate([x, y, z])}
""")



Concatenamos `x` e `y`:
[1 2 3 3 2 1]

Concatenamos `x`, `y` y `z`:
[ 1  2  3  3  2  1 99 99 99]



 Para arrays bidimensionales, podemos usar `np.vstack` para apilamiento vertical y `np.hstack` para apilamiento horizontal.

In [20]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(f"""
Apilamos `x` como fila encima de `grid`:
{np.vstack([x, grid])}
""")

y = np.array([[99], [99]])
print(f"""
Apilamos `y` como columna al lado de `grid`:
{np.hstack([grid, y])}
""")



Apilamos `x` como fila encima de `grid`:
[[1 2 3]
 [1 2 3]
 [4 5 6]]


Apilamos `y` como columna al lado de `grid`:
[[ 1  2  3 99]
 [ 4  5  6 99]]



 La división de arrays se realiza con `np.split`, `np.hsplit` y `np.vsplit`.

In [21]:
"""
Dividimos `x` en tres partes y mostramos los subarrays resultantes.
"""

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # Dividimos `x` en tres partes.

print(f"""
Subarray x1: {x1}
Subarray x2: {x2}
Subarray x3: {x3}
""")



Subarray x1: [1 2 3]
Subarray x2: [99 99]
Subarray x3: [3 2 1]

