 # Fundamentos de los Arrays de NumPy



 La manipulación de datos en Python se asocia estrechamente con el uso de los arrays de NumPy. Muchas herramientas modernas, como Pandas, se construyen sobre la base de estos arrays, lo que hace fundamental comprender su funcionamiento. En esta sección, exploraremos cómo acceder a los datos y subarrays, así como cómo dividir, reorganizar y combinar arrays. Aunque estas operaciones básicas pueden parecer simples, constituyen los pilares para tareas más avanzadas y sofisticadas. Familiarízate bien con ellas para aprovechar al máximo NumPy.



 A continuación, cubriremos varias categorías de manipulación de arrays:



 - **Atributos de arrays**: Cómo determinar el tamaño, forma, consumo de memoria y tipos de datos de los arrays.

 - **Indexación de arrays**: Cómo obtener y modificar elementos individuales de un array.

 - **Rebanado (slicing) de arrays**: Cómo acceder y modificar subarrays.

 - **Reorganización de arrays**: Cómo cambiar la forma de un array existente.

 - **Unión y división de arrays**: Cómo combinar múltiples arrays en uno o dividir uno en varios.

 ## Atributos de los Arrays en NumPy



 Vamos a empezar definiendo tres arrays aleatorios de una, dos y tres dimensiones, utilizando el generador de números aleatorios de NumPy. Utilizaremos una semilla para garantizar que se generen los mismos números cada vez que ejecutemos el código.

In [1]:
import numpy as np  # Importamos la biblioteca NumPy y la referenciamos con el alias 'np'.

rng = np.random.default_rng(0)  # Creamos un generador de números aleatorios con una semilla fija.
x1 = rng.integers(10, size=6)  # Array unidimensional con 6 elementos aleatorios entre 0 y 9.
x2 = rng.integers(10, size=(3, 4))  # Array bidimensional de tamaño 3x4 con elementos aleatorios.
x3 = rng.integers(10, size=(3, 4, 5))  # Array tridimensional de tamaño 3x4x5 con elementos aleatorios.


 Atributos útiles de `x3`:

In [2]:
x3.ndim  # Muestra el número de dimensiones del array `x3`.


3

In [3]:
x3.shape  # Muestra el tamaño de cada dimensión del array `x3`.


(3, 4, 5)

In [4]:
x3.size  # Muestra el número total de elementos en el array `x3`.


60

 Tipo de datos (`dtype`) de `x3`:

In [5]:
x3.dtype  # Muestra el tipo de datos de los elementos en `x3`.


dtype('int64')

 Tamaño en bytes (`itemsize`) y tamaño total (`nbytes`) de `x3`:

In [6]:
x3.itemsize  # Tamaño en bytes de cada elemento del array `x3`.


8

In [7]:
x3.nbytes  # Tamaño total en bytes del array `x3`.


480

 ## Indexación de Arrays: Acceso a Elementos Individuales



 La indexación de elementos en un array de NumPy es similar a la indexación en listas de Python. En un array unidimensional, puedes acceder al elemento en la posición `i` usando corchetes.

In [8]:
x1  # Mostramos el array `x1`.


array([8, 6, 5, 2, 3, 0], dtype=int64)

In [9]:
x1[0]  # Accedemos al primer elemento del array `x1`.


8

In [10]:
x1[4]  # Accedemos al quinto elemento del array `x1`.


3

 También podemos usar índices negativos para acceder a los elementos desde el final del array.

In [11]:
x1[-1]  # Último elemento del array `x1`.


0

In [12]:
x1[-2]  # Penúltimo elemento del array `x1`.


3

 En arrays multidimensionales, accedemos a los elementos mediante una tupla de índices separados por comas.

In [13]:
x2  # Mostramos el array bidimensional `x2`.


array([[0, 0, 1, 8],
       [6, 9, 5, 6],
       [9, 7, 6, 5]], dtype=int64)

In [14]:
x2[0, 0]  # Primer elemento de la primera fila del array `x2`.


0

In [15]:
x2[2, 0]  # Primer elemento de la tercera fila del array `x2`.


9

In [16]:
x2[2, -1]  # Último elemento de la tercera fila del array `x2`.


5

 Podemos modificar los valores de los elementos utilizando la misma notación de índice.

In [17]:
x2[0, 0] = 12  # Modificamos el primer elemento de la primera fila de `x2`.
x2  # Mostramos el array modificado `x2`.


array([[12,  0,  1,  8],
       [ 6,  9,  5,  6],
       [ 9,  7,  6,  5]], dtype=int64)

 A diferencia de las listas de Python, los arrays de NumPy tienen un tipo de dato fijo. Esto significa que si intentamos asignar un valor de un tipo diferente, se realizará una conversión automática, posiblemente truncando el valor.

In [18]:
x1[0] = 3.14159  # El valor de punto flotante será truncado al convertirlo a un entero.
x1  # Mostramos el array `x1` después de asignar un valor de punto flotante truncado.


array([3, 6, 5, 2, 3, 0], dtype=int64)

 ## Rebanado (Slicing) de Arrays: Acceso a Subarrays



 Podemos acceder a subarrays utilizando la notación de slicing (rebanado) con el carácter `:`. La sintaxis general para un slicing es `x[start:stop:step]`.

In [19]:
x = np.arange(10)  # Creamos un array con valores del 0 al 9.
x[:5]  # Primeros cinco elementos.


array([0, 1, 2, 3, 4])

In [20]:
x[5:]  # Elementos a partir del índice 5.


array([5, 6, 7, 8, 9])

In [21]:
x[4:7]  # Subarray del índice 4 al 6.


array([4, 5, 6])

In [22]:
x[::2]  # Elementos con paso de 2.


array([0, 2, 4, 6, 8])

In [23]:
x[1::2]  # Elementos a partir del índice 1 con paso de 2.


array([1, 3, 5, 7, 9])

 El paso negativo nos permite invertir el orden del array.

In [24]:
x[::-1]  # Mostrar el array `x` en orden inverso.


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x[5::-2]  # Mostrar los elementos en orden inverso desde el índice 5 con paso de 2.


array([5, 3, 1])

 ## Subarrays Multidimensionales



 Los subarrays en arrays multidimensionales funcionan de manera similar, pero podemos aplicar múltiples slicing separados por comas.

In [26]:
x2[:2, :3]  # Primeras dos filas y primeras tres columnas de `x2`.


array([[12,  0,  1],
       [ 6,  9,  5]], dtype=int64)

In [27]:
x2[:, ::2]  # Todas las filas, cada dos columnas.


array([[12,  1],
       [ 6,  5],
       [ 9,  6]], dtype=int64)

 También podemos invertir dimensiones combinando slicing.

In [28]:
x2[::-1, ::-1]  # Invierte filas y columnas del array `x2`.


array([[ 5,  6,  7,  9],
       [ 6,  5,  9,  6],
       [ 8,  1,  0, 12]], dtype=int64)

 ## Acceso a Filas y Columnas en Arrays



 Es común acceder a filas o columnas individuales. Esto se puede lograr combinando la indexación y el slicing.

In [29]:
x2[:, 0]  # Primera columna de `x2`.


array([12,  6,  9], dtype=int64)

In [30]:
x2[0, :]  # Primera fila de `x2`.


array([12,  0,  1,  8], dtype=int64)

In [31]:
x2[0]  # Equivalente a `x2[0, :]`.


array([12,  0,  1,  8], dtype=int64)

 ## Subarrays como Vistas Sin Copias



 Cuando realizamos slicing de un array en NumPy, se crea una vista, no una copia. Esto significa que las modificaciones en el subarray afectan al array original.

In [32]:
x2_sub = x2[:2, :2]  # Extraemos un subarray 2x2.
x2_sub  # Mostramos el subarray extraído.


array([[12,  0],
       [ 6,  9]], dtype=int64)

In [33]:
x2_sub[0, 0] = 99  # Modificamos el subarray.
x2_sub  # Mostramos el subarray modificado.


array([[99,  0],
       [ 6,  9]], dtype=int64)

In [34]:
x2  # El array original se ve afectado.


array([[99,  0,  1,  8],
       [ 6,  9,  5,  6],
       [ 9,  7,  6,  5]], dtype=int64)

 Si necesitamos una copia del subarray para que los cambios no afecten al array original, podemos usar `copy()`.

In [35]:
x2_sub_copy = x2[:2, :2].copy()  # Creamos una copia del subarray.
x2_sub_copy[0, 0] = 42  # Modificamos la copia.
x2_sub_copy  # Mostramos la copia del subarray modificada.


array([[42,  0],
       [ 6,  9]], dtype=int64)

In [36]:
x2  # El array original no se ve afectado.


array([[99,  0,  1,  8],
       [ 6,  9,  5,  6],
       [ 9,  7,  6,  5]], dtype=int64)

 ## Reorganización de Arrays



 Podemos cambiar la forma de un array con el método `reshape()`. Por ejemplo, podemos reorganizar números del 1 al 9 en una cuadrícula de 3x3.

In [37]:
grid = np.arange(1, 10).reshape((3, 3))
grid  # Mostramos la cuadrícula.


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 Conversión de arrays unidimensionales a matrices de fila o columna.

In [38]:
x1 = np.array([1, 2, 3])
x1.reshape((1, 3))  # Convertimos `x1` en un vector fila usando reshape.


array([[1, 2, 3]])

In [39]:
x1[np.newaxis, :]  # Usamos `np.newaxis` para convertirlo en un vector fila.


array([[1, 2, 3]])

In [40]:
x1.reshape((3, 1))  # Convertimos `x1` en un vector columna usando reshape.


array([[1],
       [2],
       [3]])

In [41]:
x1[:, np.newaxis]  # Usamos `np.newaxis` para convertirlo en un vector columna.


array([[1],
       [2],
       [3]])

 ## Concatenación y División de Arrays



 Podemos combinar múltiples arrays en uno con funciones como `np.concatenate`, `np.vstack` y `np.hstack`, y también dividir un array en varios subarrays.

In [42]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
np.concatenate([x, y])  # Concatenamos `x` e `y`.


array([1, 2, 3, 3, 2, 1])

In [43]:
np.concatenate([x, y, z])  # Concatenamos `x`, `y` y `z`.


array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

 Para arrays bidimensionales, podemos usar `np.vstack` para apilamiento vertical y `np.hstack` para apilamiento horizontal.

In [44]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.vstack([x, grid])  # Apilamos `x` como fila encima de `grid`.


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
y = np.array([[99], [99]])
np.hstack([grid, y])  # Apilamos `y` como columna al lado de `grid`.


array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

 La división de arrays se realiza con `np.split`, `np.hsplit` y `np.vsplit`.

In [46]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # Dividimos `x` en tres partes.


In [47]:
x1

array([1, 2, 3])

In [48]:
x2

array([99, 99])

In [49]:
x3

array([3, 2, 1])